import json
import random

# Define the number of reviews to generate
NUM_REVIEWS = 500


# Define the list of unique comments
RATING = random.randint(1, 5), 
COMMENTS = [
    "Absolutely great value for the price.",
    "Absolutely no complaints.",
    "Absolutely pretty decent overall — would buy again.",
    "Absolutely satisfied with the quality and performance.",
    "Absolutely item arrived in good condition and on time.",
    "Absolutely nothing extraordinary.",
    "Absolutely solid product — meets my expectations.",
    "Absolutely good packaging and fast delivery.",
    "Absolutely no major issues so far.",
    "Absolutely reliable.",
    "Absolutely fairly priced for what you get.",
    "Absolutely decent, would recommend.",
    "Absolutely not bad at all.",
    "Absolutely fast delivery.",
    "Absolutely it matches the description.",
    "Absolutely great choice, highly recommend!",
    "Absolutely perfect addition to my order!",
    "Absolutely so pleased.",
    "Absolutely a fantastic find online!",
    "Absolutely love how great this is!",
    "Absolutely definitely worth ordering!",
    "Absolutely super happy with this order.",
    "Absolutely a great pick every time!",
    "Really great value for the price.",
    "Really no complaints.",
    "Really pretty decent overall — would buy again.",
    "Really satisfied with the quality and performance.",
    "Really item arrived in good condition and on time.",
    "Really nothing extraordinary.",
    "Really solid product — meets my expectations.",
    "Really good packaging and fast delivery.",
    "Really no major issues so far.",
    "Really reliable.",
    "Really fairly priced for what you get.",
    "Really decent, would recommend.",
    "Really not bad at all.",
    "Really fast delivery.",
    "Really it matches the description.",
    "Really great choice, highly recommend!",
    "Really perfect addition to my order!",
    "Really so pleased.",
    "Really a fantastic find online!",
    "Really love how great this is!",
    "Really definitely worth ordering!",
    "Really super happy with this order.",
    "Really a great pick every time!",
    "Definitely great value for the price.",
    "Definitely no complaints.",
    "Definitely pretty decent overall — would buy again.",
    "Definitely satisfied with the quality and performance.",
    "Definitely item arrived in good condition and on time.",
    "Definitely nothing extraordinary.",
    "Definitely solid product — meets my expectations.",
    "Definitely good packaging and fast delivery.",
    "Definitely no major issues so far.",
    "Definitely reliable.",
    "Definitely fairly priced for what you get.",
    "Definitely decent, would recommend.",
    "Definitely not bad at all.",
    "Definitely fast delivery.",
    "Definitely it matches the description.",
    "Definitely great choice, highly recommend!",
    "Definitely perfect addition to my order!",
    "Definitely so pleased.",
    "Definitely a fantastic find online!",
    "Definitely love how great this is!",
    "Definitely definitely worth ordering!",
    "Definitely super happy with this order.",
    "Definitely a great pick every time!",
    "Excellent quality for what you pay.",
    "Just what I needed, no issues whatsoever.",
    "Pleasantly surprised by how well it works.",
    "Shipping was quick and product works as advertised.",
    "Does exactly what it claims to do.",
    "Better than expected for the price point.",
    "Simple yet effective design.",
    "Practical purchase that solved my problem.", 
    "Great customer service when I had questions.",
    "Straightforward setup and easy to use.",
    "Functional and well-made product.",
    "Impressed with the durability so far.",
    "Exactly as pictured in the listing.",
    "Performs consistently every time.",
    "Good value compared to similar products.",
    "Hassle-free transaction from start to finish.",
    "Sturdy construction that should last.",
    "Very pleased with this purchase overall.",
    "Does the job without any fuss.",
    "Convenient solution for everyday use.",
    "Quality exceeded my expectations.",
    "Works perfectly for its intended purpose.",
    "Thoughtful design with practical features.",
    "Prompt delivery and item as described.",
    "Reasonable price for the functionality offered.",
    "Solid performance since day one.",
    "Fits perfectly where I needed it.",
    "User-friendly and intuitive operation.",
    "Well worth the investment.",
    "Smooth transaction and product works great.",
    "Clever design that saves time and effort.",
    "Completely satisfied with this purchase.",
    "Everything I was looking for in one package.",
    "Happy with both quality and service.",
    "Meets all my requirements perfectly." ,
    "Compact yet fully functional.",
    "Clean design with attention to detail.",
    "Exceptional value for everyday use.",
    "Makes life easier, just as promised." ,
    "Practical addition to my home/office.",
    "Precisely what the description promised.",
    "Couldn't ask for better performance.",
    "A worthwhile purchase I don't regret.",
    "Attractive design that also functions well.",
    "Perfect fit for my specific needs.",
    "Consistently reliable since I bought it.",
    "Seamless ordering and delivery process.",
    "Impressive attention to the small details.",
    "Wonderful balance of price and quality.",
    "Helpful product that simplifies daily tasks.",
    "Well-engineered and thoughtfully designed.",
    "Pleasantly surprised by the craftsmanship.",
    "Exceeded my modest expectations.",
    "A good investment that pays for itself.",
    "No regrets with this purchase whatsoever.",
    "Lives up to all the positive reviews.",
    "Remarkably efficient for such a simple device.",
    "Elegant solution to a common problem.",
    "Fantastic value without compromising quality.",
    "Functions flawlessly right out of the box." ,
    "Much better than similar products I've tried.",
    "Nicely packaged and arrived in perfect condition.",
    "Effective solution at a reasonable cost.",
    "Intuitive design makes it easy to operate.",
    "Outstanding performance for everyday use.",
    "Fulfills its purpose without complications.",
    "Noticeably improved my daily routine.",
    "Well worth every penny spent.",
    "Convenient features that make a difference.",
    "Consistently delivers what it promises.",
    "Precisely engineered for optimal performance.",
    "Handles its intended task with ease.",
    "Truly satisfied with this purchase.",
    "Intelligent design that considers the user.",
    "Practical functionality without unnecessary frills.",
    "Ideal balance between cost and capabilities.",
    "Operates smoothly with no hiccups.",
    "Recommended for anyone needing this type of product.",
    "Surprisingly versatile for multiple purposes.",
    "Efficient design that saves time and effort.",
    "Genuinely pleased with this acquisition.",
    "First-rate quality at a fair price.",
    "More useful than I initially expected.",
    "Perfectly suited for my specific situation.",
    "Reliable performance day after day.",
    "Fantastic purchase that meets all needs.",
    "Well-constructed with quality materials.",
    "Simplifies tasks without any complications.",
    "Exactly the solution I was searching for.",
    "Thoughtfully designed with the user in mind.",
    "Highly functional without being overly complex.",
    "Surpassed my initial expectations.",
    "Practical purchase that proves its worth daily.",
    "Remarkable efficiency for routine tasks.",
    "Elegant design that's also highly practical.",
    "Performance justifies the price point.",
    "Consistently reliable since purchase date.",
    "Appreciate the attention to user experience.",
    "Perfect balance of form and function.",
    "Delighted with how well it performs.",
    "Exceptional craftsmanship at this price point.",
    "Serves its purpose admirably well.",
    "Delivered promptly and works as expected.",
    "Impressive quality for everyday use.",
    "Smart design that anticipates user needs.",
    "Thoroughly satisfied with this investment.",
    "Works reliably without any issues.",
    "Excellent addition to my daily routine.",
    "Skillfully designed for maximum utility.",
    "Stands up well to regular usage.",
    "Terrific value that exceeds expectations.",
    "Useful features that enhance functionality.",
    "Precisely what I was looking for.",
    "Remarkable performance for such a simple item.",
    "Effortless to integrate into daily use.",
    "Sturdy build quality that inspires confidence.",
    "Performs its function without fail.",
    "Genuinely happy with this purchase.",
    "Well-executed design and functionality.",
    "Exceeds expectations in every aspect.",
    "Practical tool that serves its purpose well.",
    "Notably efficient performance every time.",
    "Superb quality for the price point.",
    "Particularly pleased with the reliability.",
    "Skillfully crafted for optimal use.",
    "Daily use proves its worth continually.",
    "Excellent performance right from the start.",
    "Appreciably better than previous versions.",
    "Utterly dependable for its intended purpose.",
    "Intelligently designed for user convenience.",
    "Worth every dollar spent on this purchase.",
    "Admirable quality and workmanship.",
    "Wonderfully practical for everyday needs.",
    "Does what it should without complications.",
    "Solidly constructed for lasting performance.",
    "Perfectly functional and reasonably priced.",
    "Impressive attention to practical details.",
    "Handles tasks efficiently and reliably.",
    "Remarkably simple yet highly effective.",
    "Well-executed design from top to bottom.",
    "Truly satisfied with this practical purchase.",
    "Entirely suitable for my specific needs.",
    "Performs consistently day after day.",
    "Exceptional value for such quality.",
    "Delivered promptly and works perfectly.",
    "Particularly useful addition to my collection.",
    "Thoughtfully engineered for ease of use.",
    "Outstanding performance for the investment.",
    "Exactly matches the product description.",
    "Very pleased with its overall utility.",
    "Easily integrates into my daily routine.",
    "Surprisingly effective for such a simple item.",
    "Well-designed solution that works perfectly.",
    "Truly an excellent investment decision.",
    "Exceedingly practical for regular use.",
    "Noticeably improves efficiency in its task.",
    "Quality construction that should endure.",
    "Genuinely impressed with the performance.",
    "Functions exactly as advertised.",
    "Remarkably user-friendly design.",
    "Works consistently without any problems.",
    "Excellent value proposition overall.",
    "Perfectly suited to its intended purpose.",
    "Quite pleased with this practical purchase.",
    "Solidly built for lasting performance.",
    "Admirably effective for daily tasks.",
    "Functions reliably each and every time.",
    "Worth recommending to friends and family.",
    "Notably efficient in performing its job.",
    "Precisely what was needed and expected.",
    "Exceptional performance day after day.",
    "Very satisfied with the purchase decision.",
    "Well thought out design and execution.",
    "Performs its function admirably well.",
    "Quite impressive for such a simple product.",
    "Delightfully useful addition to my home.",
    "Consistently dependable performance.",
    "Remarkable value at this price point.",
    "Fits perfectly into its intended space.",
    "Incredibly useful for its designed purpose.",
    "Especially pleased with the overall quality.",
    "Thoughtfully designed for maximum utility.",
    "Absolutely delivers on its promises.",
    "Particularly effective solution for my needs.",
    "Works wonderfully well every time.",
    "Thoughtfully engineered for user satisfaction.",
    "Notably better than previous models.",
    "Pleasantly practical for everyday use.",
    "Excellent performance without any issues.",
    "Particularly useful design features.",
    "Precisely fabricated for optimal function.",
    "Truly a worthwhile purchase decision.",
    "Consistently reliable for its purpose.",
    "Greatly enhances my daily routine.",
    "Well-executed from concept to delivery.",
    "Performs flawlessly as intended.",
    "Remarkably efficient for routine tasks.",
    "Particularly well-suited to my needs.",
    "Solidly constructed with quality materials." 
    "Satisfyingly effective for daily use.",
    "Expertly designed for practical application.",
    "Works smoothly with no complications.",
    "Just right for my specific requirements.",
    "Impressively capable for such a simple item.",
    "Wonderfully practical addition to my toolkit.",
    "Delivers consistent results every time.",
    "Exemplary performance since purchase.",
    "Notably good value for the investment.",
    "Perfectly functional in every respect.",
    "Decidedly pleased with this acquisition.",
    "Especially effective for its intended use.",
    "Wholly satisfactory in all aspects.",
    "Intelligently designed for user convenience.",
    "Performs reliably day after day.",
    "Excellent addition to my daily operations.",
    "Precisely what I was hoping for.",
    "Remarkably well-executed design.",
    "Highly functional without unnecessary complexity.",
    "Genuinely satisfied with this purchase.",
    "Skillfully engineered for optimal use.",
    "Consistently delivers expected results.",
    "Worth every cent of the purchase price.",
    "Perfectly suited to my particular needs.",
    "Notably efficient in everyday use.",
    "Well-built with attention to durability.",
    "Performs its function without fail.",
    "Especially happy with the overall value.",
    "Exactly matches my requirements.",
    "Remarkably useful addition to my home.",
    "Superbly designed for practical application.",
    "Works exactly as it should, no issues.",
    "Particularly pleased with its reliability.",
    "Thoughtfully constructed for lasting use.",
    "Functions smoothly in daily operation.",
    "Decidedly worth the investment made.",
    "Notably effective at its intended purpose.",
    "Well worth recommending to others.",
    "Perfectly adequate for my needs.",
    "Impressively reliable since purchase.",
    "Especially useful for specific tasks.",
    "Well-engineered solution that works well.",
    "Consistently dependable performance.",
    "Remarkably practical for everyday use.",
    "Exactly the quality I was expecting.",
    "Truly satisfied with overall performance.",
    "Intelligently designed with users in mind.",
    "Works efficiently without complications.",
    "Particularly good value for the money.",
    "Skillfully manufactured for durability.",
    "Functions perfectly every single time.",
    "Genuinely pleased with this product.",
    "Remarkably effective solution for daily needs.",
    "Well-executed design in every respect.",
    "Precisely engineered for optimal function.",
    "Decidedly helpful for my specific purpose.",
    "Consistently performs as promised.",
    "Notably well-designed for ease of use.",
    "Worth the price for the quality received.",
    "Perfectly suited to regular usage.",
    "Especially impressed with the craftsmanship.",
    "Thoughtfully conceived for practical application.,"
    "Works without any hiccups or issues.",
    "Particularly satisfied with this purchase.",
    "Well-made with attention to detail.",
    "Functions reliably for its intended use.",
    "Decidedly better than expected.",
    "Notably efficient in performing tasks.",
    "Well worth the investment made.",
    "Perfectly adequate for daily requirements.",
    "Impressively durable in regular use.",
    "Especially useful tool for specific needs.",
    "Well-engineered for optimal performance.",
    "Consistently delivers excellent results.",
    "Remarkably practical addition to my setup.",
    "Exactly what was needed and wanted.",
    "Truly delighted with this purchase.",
    "Intelligently designed for maximum utility.",
    "Works effectively without complication.",
    "Skillfully crafted for lasting performance.",
    "Functions flawlessly as intended.",
    "Genuinely impressed with overall quality.",
    "Remarkably efficient for its purpose.",
    "Well-executed from design to delivery.",
    "Precisely what the description promised.",
    "Decidedly useful for everyday tasks.",
    "Consistently reliable in performance.",
    "Notably well-constructed and durable.",
    "Worth recommending without reservation.",
    "Perfectly matched to my expectations.",
    "Especially effective solution for daily use.",
    "Thoughtfully designed with practical intent.",
    "Works exactly as described, no issues.",
    "Particularly pleased with this product.",
    "Well-made with quality components.",
    "Functions reliably day after day.",
    "Decidedly satisfied with this purchase.",
    "Notably efficient for routine tasks.",
    "Well worth the price paid.",
    "Perfectly suited to my specific needs.",
    "Impressively effective in regular use.",
    "Especially practical for daily application.",
    "Well-engineered for user convenience.",
    "Consistently performs without fail.",
    "Remarkably useful addition to my inventory.",
    "Exactly the solution I was seeking.",
    "Truly satisfactory in every respect.",
    "Intelligently designed for optimal function.",
    "Works smoothly with zero problems.",
    "Particularly good quality for the price.",
    "Skillfully manufactured to last.",
    "Functions exactly as advertised.",
    "Genuinely happy with this product.",
    "Remarkably versatile for multiple uses.",
    "Well-executed concept and delivery.",
    "Precisely what I needed for this purpose.",
    "Decidedly enhances my daily routine.",
    "Consistently dependable in operation.",
    "Notably practical for everyday use.",
    "Worth every penny of the purchase price.",
    "Perfectly functional in all respects.",
    "Especially impressed with its performance.",
    "Thoughtfully conceived for user satisfaction.",
    "Works reliably without any issues.",
    "Particularly satisfied with the value.",
    "Well-constructed for durability.",
    "Functions admirably for its purpose.",
    "Decidedly pleased with this acquisition.",
    "Notably efficient and effective.",
    "Well worth recommending to others.",
    "Perfectly meets all my requirements.",
    "Impressively reliable day after day.",
    "Especially useful for specific applications.",
    "Well-designed solution that works perfectly.",
    "Consistently delivers expected performance.",
    "Remarkably practical for regular use.",
    "Exactly what was described and needed.",
    "Truly impressed with the overall quality.",
    "Intelligently engineered for ease of use.",
    "Works flawlessly every single time.",
    "Particularly good investment decision.",
    "Skillfully designed for practical application.",
    "Functions without any complications.",
    "Genuinely satisfied with this purchase.",
    "Remarkably effective for daily tasks.",
    "Well-executed in design and function.",
    "Precisely what I was looking for.",
    "Decidedly valuable addition to my home.",
    "Consistently performs as intended.",
    "Notably well-made and durable.",
    "Worth the price for the quality delivered.",
    "Perfectly suitable for my specific needs.",
    "Especially effective at its intended purpose.",
    "Thoughtfully designed with users in mind.",
    "Works exactly as described, no disappointments.",
    "Particularly pleased with this product.",
    "Well-built with attention to detail.",
    "Functions reliably in daily use.",
    "Decidedly better than similar products.",
    "Notably efficient for routine applications.",
    "Well worth the investment made.",
    "Perfectly adequate for my requirements.",
    "Impressively durable under regular use.",
    "Especially practical solution for daily needs.",
    "Well-engineered for optimal performance.",
    "Consistently delivers quality results.",
    "Remarkably useful addition to my collection.",
    "Exactly the quality I was hoping for.",
    "Truly happy with this purchase decision.",
    "Intelligently designed for practical use.",
    "Works smoothly without any issues.",
    "Particularly good value for money.",
    "Skillfully manufactured for longevity.",
    "Functions perfectly for its intended purpose.",
    "Genuinely impressed with the craftsmanship.",
    "Remarkably effective in everyday use.",
    "Well-executed from concept to production.",
    "Precisely engineered for its function.",
    "Decidedly helpful for specific tasks.",
    "Consistently reliable performance.",
    "Notably well-designed and practical.",
    "Worth recommending for its quality.",
    "Perfectly matched to my expectations.",
    "Especially satisfied with its utility.",
    "Thoughtfully constructed for durability.",
    "Works without any complications.",
    "Particularly pleased with this purchase.",
    "Well-made with quality materials.",
    "Functions reliably every time.",
    "Decidedly worth the price paid.",
    "Notably efficient at what it does.",
    "Well worth adding to my collection.",
    "Perfectly suited to daily use.",
    "Impressively effective for its purpose.",
    "Especially useful for specific applications.",
    "Well-designed for user convenience.",
    "Consistently performs as expected.",
    "Remarkably practical addition to my toolkit.",
    "Exactly what I needed for this task.",
    "Truly satisfied with the purchase.",
    "Intelligently engineered for optimal function.",
    "Works flawlessly in all conditions.",
    "Particularly good product overall.",
    "Skillfully designed for maximum utility.",
    "Functions exactly as described.",
    "Genuinely happy with this investment.",
    "Remarkably versatile in application.",
    "Well-executed in every respect.",
    "Precisely what the seller promised.",
    "Decidedly enhances my daily activities.",
    "Consistently dependable in operation.",
    "Notably practical for regular use.",
    "Worth every cent invested.",
    "Perfectly functional for my needs.",
    "Especially impressed with the design.",
    "Thoughtfully conceived for practical use.",
    "Works reliably day after day.",
    "Particularly satisfied with this product.",
    "Well-constructed for lasting performance.",
    "Functions admirably well for its purpose.",
    "Decidedly pleased with this choice.",
    "Notably efficient in daily application.",
    "Well worth the purchase price.",
    "Perfectly adequate for intended use.",
    "Impressively reliable since acquisition.",
    "Especially effective solution for specific tasks.",
    "Well-engineered with attention to detail.",
    "Consistently delivers solid performance.",
    "Remarkably useful for everyday needs.",
    "Exactly as described and expected.",
    "Truly impressed with overall quality.",
    "Intelligently designed for user satisfaction.",
    "Works smoothly in all situations.",
    "Particularly good value proposition." ,
    "Skillfully manufactured with quality materials." ,
    "Functions perfectly without issues." ,
    "Genuinely satisfied with this acquisition.",
    "Remarkably effective for its intended use.",
    "Well-executed design and implementation.",
    "Precisely what I was searching for.",
    "Decidedly valuable addition to my setup.",
    "Consistently performs without problems.",
    "Notably well-made and durable.",
    "Worth recommending to anyone interested.",
    "Perfectly matched to my requirements.",
    "Especially pleased with its performance.",
    "Thoughtfully designed for optimal function.",
    "Works exactly as advertised, no surprises.",
    "Particularly happy with this product.",
    "Well-built to withstand regular use.",
    "Functions reliably in daily operation.",
    "Decidedly better than expected.",
    "Notably efficient for routine tasks.",
    "Well worth the money spent.",
    "Perfectly suited to my specific needs.",
    "Impressively durable under heavy use.",
    "Especially practical for everyday application.",
    "Well-engineered for user convenience.",
    "Consistently delivers expected results.",
    "Remarkably useful addition to my home.",
    "Exactly the solution I needed.",
    "Truly delighted with this purchase.",
    "Intelligently designed with practical intent.",
    "Works flawlessly every time.",
    "Particularly good quality for the price.",
    "Skillfully crafted for lasting use.",
    "Functions exactly as described.",
    "Genuinely impressed with this product.",
    "Remarkably effective in daily use.",
    "Well-executed from start to finish.",
    "Precisely engineered for its purpose.",
    "Decidedly enhances my routine.",
    "Consistently reliable in performance.",
    "Notably practical and well-designed.",
    "Worth every dollar of the purchase price.",
    "Perfectly functional in all aspects.",
    "Especially satisfied with overall quality.",
    "Thoughtfully constructed for optimal performance.",
    "Works without any hiccups or issues.",
    "Particularly pleased with this purchase.",
    "Well-made with attention to quality.",
    "Functions reliably day after day.",
    "Decidedly worth the investment.",
    "Notably efficient at its job.",
    "Well worth adding to your collection.",
    "Perfectly suited to regular use.",
    "Impressively effective for its intended purpose.",
    "Especially useful for daily tasks.",
    "Well-designed solution that delivers.",
    "Consistently performs as promised.",
    "Remarkably practical for specific needs.",
    "Exactly as advertised and expected.",
    "Truly satisfied with this product.",
    "Intelligently engineered for ease of use.",
    "Works seamlessly in all conditions.",
    "Particularly good investment overall.",
    "Skillfully designed for maximum utility.",
    "Functions perfectly for its purpose.",
    "Genuinely happy with this purchase decision.",
    "Remarkably versatile and well-crafted.",
],

# # Shuffle the comments to ensure randomness
# random.shuffle(COMMENTS, RATING)

# Generate review data
reviews = [{"comments and review ": comment} for comment in COMMENTS[:NUM_REVIEWS]]

# Save to JSON file
with open("shop_online.json", "w") as json_file:
    json.dump(reviews, json_file, indent=4)

print(f"✅ Successfully saved {len(reviews)} unique reviews to shop_online.json")
