import json
import random

# Define the number of reviews to generate
NUM_REVIEWS = 500

def generate_review(user_id, product_id, branch_id):
    """Generate a random review based on the given table structure."""
    return {
        "user_id": user_id if random.random() > 0.1 else None,  # 10% chance of null user_id
        "branch_id": branch_id,
        "product_id": product_id,
        "rating": random.randint(1, 5),  # Ratings between 1 and 5
        "comments": random.choice([
          "Great product!",
    "Good value.",
    "Excellent service.",
    "I'm satisfied.",
    "Highly recommend.",
    "Amazing!",
    "Love it!",
    "Perfect!",
    "Exceeded my expectations!",
    "Best purchase ever!",
    "I'm impressed!",
    "Highly recommend this product to everyone!",
    "This is a game changer!",
    "So glad I bought this!",
    "This is exactly what I was looking for!",
    "I can't live without this!",
    "This is the best thing since sliced bread!",
    "This product is a must-have!",
    "I'm in love with this product!",
    "This product is life-changing!",
    "I'm so happy with this purchase!",
    "This product is amazing and I would recommend it to anyone!",
    "This product is great and I would definitely buy it again!",
    "This product is fantastic and I would recommend it to a friend!",
    "This product is awesome and I would recommend it to a family member!",
    "This product is wonderful and I would recommend it to a colleague!",
    "This product is superb and I would recommend it to a client!",
    "This product is amazing! It's exactly what I needed.",
    "I'm so impressed with the quality of this product.",
    "This product is a great value for the price.",
    "I'm very satisfied with my purchase. It arrived quickly and in perfect condition.",
    "This product is so easy to use and it works great!",
    "I'm so happy I found this product! It's made my life so much easier.",
    "This product is a must-have for anyone who needs a reliable and efficient solution.",
    "I highly recommend this product to anyone looking for a high-quality and affordable option.",
    "This product is worth every penny!",
    "I'm so glad I decided to buy this product. It's exceeded all my expectations.",
    "This product is perfect for daily use.",
    "I'm so happy with the results I've gotten from using this product.",
    "This product is a great investment.",
    "I'm so impressed with the customer service. They were very helpful and responsive.",
    "This product is a great addition to my home office.",
    "I'm so happy I took a chance on this product. It's been a game changer.",
    "This product is everything I was hoping for and more.",
    "I'm so impressed with the attention to detail in this product.",
    "This product is a great way to save time.",
    "I'm so happy I finally found a product that solves my biggest problem.",
    "This product is so much better than anything else I've tried.",
    "I'm so glad I upgraded to this product. It's been a huge improvement.",
    "This product is a great gift for anyone who appreciates quality and value.",
    "I'm so happy I can finally accomplish my goals.",
    "This product is a great way to improve my life.",
    "I'm so impressed with the innovation in this product.",
    "This product is a great example of excellent design.",
    "I'm so happy I chose this product over the competition.",
    "This product is a great value for the price. I highly recommend it.",
    "I'm very satisfied with this purchase. The product is exactly as described and works perfectly.",
    "This product is amazing! It's so easy to use and the results are fantastic.",
    "I'm so glad I bought this product. It's made my life so much easier and more enjoyable.",
    "This product is a must-have for anyone who wants to simplify their routine.",
    "I highly recommend this product to anyone looking for a reliable and high-quality solution.",
    "This product is worth every penny! It's a great investment that I'll be using for years to come.",
    "I'm so happy I decided to buy this product. It's exceeded all my expectations and I couldn't be happier with my purchase.",
    "This product is perfect for specific tasks. It's exactly what I needed and I'm so glad I found it.",
    "I'm so happy with the results I've gotten from using this product. It's helped me to become more efficient.",
    "This product is a great investment in my future. It's helped me to achieve my goals.",
    "I'm so impressed with the customer service. They were incredibly helpful and responsive to my questions and concerns.",
    "This product is a great addition to my workspace. It's helped me to be more productive.",
    "I'm so happy I took a chance on this product. It's been a game changer in my daily life.",
    "This product is everything I was hoping for and more. It's exceeded all my expectations and I'm so happy with my purchase.",
    "I'm so impressed with the attention to detail in this product. It's clear that a lot of thought and care went into its design and development.",
    "This product is a great way to save time and money. It's helped me to streamline my processes.",
    "I'm so happy I finally found a product that solves my biggest challenge. It's made a huge difference in my overall well-being.",
    "This product is so much better than anything else on the market. It's more reliable and user-friendly",
    "I'm so glad I upgraded to this product. It's been a huge improvement over my old one and I'm so happy with the results.",
    "This product is a great gift for anyone who values quality and innovation It's something they'll use and appreciate for a long time.",
    "I'm so happy I can finally focus on what matters most This product has made it possible and I'm so grateful.",
    "This product is a great way to achieve my long-term goals It's helped me to [make significant progress.",
    "I'm so impressed with the innovation in this product. It's clear that the creators are passionate about making a difference",
    "This product is a great example of quality craftsmanship. It's a testament to the brand's commitment to excellence.",
    "I'm so happy I chose this product over the competition. It's the best solution I've ever used and I'm so happy with my decision.",
    "This product is a great value for the price. I highly recommend it to anyone looking for a product that's effective and affordable.",
    "I'm very satisfied with this purchase. The product is exactly as described and works perfectly. I would definitely buy it again.",
    "This product is amazing! It's so easy to use and the results are fantastic. I'm so happy with my purchase.",
    "I'm so glad I bought this product. It's made my life so much easier and more enjoyable. I highly recommend it to others.",
    "This product is a must-have for anyone who wants to simplify their life. It's a great investment that will pay off in the long run.",
    "I highly recommend this product to anyone looking for a reliable and high-quality product. It's a great value for the price and I'm very happy with my purchase.",
    "This product is worth every penny! It's a great investment that I'll be using for years to come. I'm so happy with its performance and durability.",
    "I'm so happy I decided to buy this product. It's exceeded all my expectations and I couldn't be happier with my purchase. I highly recommend it to anyone looking for a effective solution.",
    "This product is perfect for everyday use. It's exactly what I needed and I'm so glad I found it. It's made a huge difference in my daily routine.",
    "I'm so happy with the results I've gotten from using this product. It's helped me to improve my efficiency. I'm so grateful for its ease of use.",
    "This product is a great investment",
    "This deserves all the positive reviews it gets!",
    "So simple yet so effective. Love it!",
    "A must-have for anyone who values reliability.",
    "I was skeptical at first, but this exceeded my expectations.",
    "Trust me, you won't regret this purchase!",
    "I use this every day, and it's been a game-changer.",
    "The customer support was fantastic, and the product is excellent.",
    "Not just good—it's amazing! So glad I got this.",
    "It does exactly what it says. Couldn't ask for more!",
    "High quality, reliable, and easy to use. Perfect!",
    "An absolute must-have! I'm so glad I took the plunge.",
    "So worth the price! You won't be disappointed.",
    "One of the best purchases I've ever made. Worth every penny.",
    "No regrets at all. In fact, I'm about to buy another one.",
    "Totally worth it! I can't recommend it enough.",
    "Amazing craftsmanship and attention to detail.",
    "I've tried similar products, and this one is by far the best.",
    "Incredible value for the price. Highly recommend!",
    "No regrets at all. In fact, I'm about to buy another one.",
    "Couldn't have asked for a better product!",
    "Superb in every way. I'm genuinely impressed!",
    "This deserves all the positive reviews it gets!",
    "So simple yet so effective. Love it!",
    "Perfect in every way. I will be purchasing again.",
    "Fantastic quality. Would give it 10 stars if I could!",
    "It's perfect in every way! I wouldn't change a thing.",
    "The positive reviews were right—this is excellent!",
    "A high-quality product that delivers on its promises.",
    "Very happy with my purchase! Would recommend to anyone.",
    "A high-quality product that delivers on its promises.",
    "A must-have item in my daily routine. It's been amazing.",
    "Well worth the money! Will be purchasing again.",
    "So worth the price! You won't be disappointed.",
    "An excellent buy. I would happily purchase this again.",
    "This product proves that quality still exists!",
    "Incredible value for the price. Highly recommend!",
    "A must-have item in my daily routine. It's been amazing.",
    "It's perfect in every way! I wouldn't change a thing.",
    "It does what it promises, and then some!",
    "A friend recommended this, and now I see why!",
    "I never write reviews, but this product deserves one.",
    "Superb quality and fast shipping. Couldn't be happier!",
    "It does what it promises, and then some!",
    "Very happy with my purchase! Would recommend to anyone.",
    "If you're considering it, just go for it. You won't look back!",
    "Trust me, you won't regret this purchase!",
    "A friend recommended this, and now I see why!",
    "This deserves all the positive reviews it gets!",
    "A friend recommended this, and now I see why!",
    "This product proves that quality still exists!",
    "One of the best purchases I've ever made. Worth every penny.",
    "I love when products actually live up to the hype!",
    "I never write reviews, but this product deserves one.",
    "It does what it promises, and then some!",
    "Well worth the money! Will be purchasing again.",
    "It does exactly what it says. Couldn't ask for more!",
    "The positive reviews were right—this is excellent!",
    "A high-quality product that delivers on its promises.",
    "Every detail is perfect. Well done!",
    "From the moment I received it, I knew it was a great buy.",
    "I appreciate the attention to detail. It really makes a difference.",
    "This has been a lifesaver for me. I use it every day!",
    "I've never been this satisfied with a purchase before.",
    "I didn't expect it to be this good, but I was pleasantly surprised.",
    "I love products that make things simple. This is one of them.",
    "I've been raving about this to my friends and family!",
    "It does what it promises, and then some!",
    "The customer support was fantastic, and the product is excellent.",
    "If you're considering it, just go for it. You won't look back!",
    "I was hoping for something decent, but this is incredible!",
    "Finally found something that actually delivers!",
    "This product is a gem! I wish I had bought it sooner.",
    "So simple yet so effective. Love it!",
    "This product is a gem! I wish I had bought it sooner.",
    "From the moment I received it, I knew it was a great buy.",
    "I've recommended this to so many people already!",
    "I've tried similar products, and this one is by far the best.",
    "This exceeded my expectations. A great investment!",
    "Finally found something that actually delivers!",
    "A high-quality product that delivers on its promises.",
    "A must-have item in my daily routine. It's been amazing.",
    "It does exactly what it says. Couldn't ask for more!",
    "I've never been this satisfied with a purchase before.",
    "This deserves all the positive reviews it gets!",
    "High quality, reliable, and easy to use. Perfect!",
    "A high-quality product that delivers on its promises.",
    "I'm blown away by how well this works. Fantastic!",
    "Very impressed! Will definitely buy again.",
    "Great purchase. It's made my life much easier.",
    "I was hoping for something decent, but this is incredible!",
    "Trust me, you won't regret this purchase!",
    "The customer support was fantastic, and the product is excellent.",
    "Very happy with my purchase! Would recommend to anyone.",
    "It's perfect in every way! I wouldn't change a thing.",
    "I was so happy with this that I ordered another one!",
    "This has been a lifesaver for me. I use it every day!",
    "Couldn't have asked for a better product!",
    "I appreciate the attention to detail. It really makes a difference.",
    "You can tell this was made with care and quality in mind.",
    "Absolutely love this product! It works just as advertised.",
    "I keep recommending this to friends because it's that good.",
    "It's rare to find something this good at this price.",
    "Well worth the money! Will be purchasing again.",
    "Every detail is perfect. Well done!",
    "I've never been this satisfied with a purchase before.",
    "This is easily one of the best things I own.",
     "A must-have item in my daily routine. It's been amazing.",
    "This product has made my life so much easier. Thank you!",
    "This has been a lifesaver for me. I use it every day!",
    "I've been raving about this to my friends and family!",
    "The positive reviews were right—this is excellent!",
    "I was hoping for something decent, but this is incredible!",
    "I was hesitant, but now I can't imagine being without it.",
    "Every aspect of this product is well thought out.",
    "This is easily one of the best things I own.",
    "So worth the price! You won't be disappointed.",
    "The customer support was fantastic, and the product is excellent.",
    "So convenient and easy to use. A game-changer!",
    "I use this every day, and it's been a game-changer.",
    "Five stars all the way! A fantastic purchase.",
    "I was hoping for something decent, but this is incredible!",
    "Surprisingly good! Exceeded my expectations in every way.",
    "I'm blown away by how well this works. Fantastic!",
    "This product has become an essential part of my day.",
    "A high-quality product that delivers on its promises.",
    "The positive reviews were right—this is excellent!",
    "The reviews didn't lie—this is fantastic!",
    "Bought this as a gift, and the recipient loved it!",
    "Love the design and functionality. Such a great find!",
    "It does exactly what it says. Couldn't ask for more!",
    "A must-have item in my daily routine. It's been amazing.",
    "The customer support was fantastic, and the product is excellent.",
    "Totally satisfied! Will be buying more for my family.",
    "Very impressed! Will definitely buy again.",
    "It's perfect in every way! I wouldn't change a thing.",
    "If you're on the fence, just buy it. You won't regret it.",
    "I love products that make things simple. This is one of them.",
    "I've been raving about this to my friends and family!",
    "You can tell this was made with care and quality in mind.",
    "One of the best purchases I've ever made. Worth every penny.",
    "I didn't expect it to be this good, but I was pleasantly surprised.",
    "I love products that make things simple. This is one of them.",
    "I've been raving about this to my friends and family!",
    "It does what it promises, and then some!",
    "The customer support was fantastic, and the product is excellent.",
    "If you're considering it, just go for it. You won't look back!",
    "I was hoping for something decent, but this is incredible!",
    "I was hesitant, but now I can't imagine being without it.",
    "I'm blown away by how well this works. Fantastic!",
    "Finally found something that actually delivers!",
    "This product is a gem! I wish I had bought it sooner.",
    "So simple yet so effective. Love it!",
    "I've recommended this to so many people already!",
    "I've tried similar products, and this one is by far the best.",
    "This exceeded my expectations. A great investment!",
    "Finally found something that actually delivers!",
    "A high-quality product that delivers on its promises.",
    "An absolute must-have! I'm so glad I took the plunge.",
    "A must-have item in my daily routine. It's been amazing.",
    "It does exactly what it says. Couldn't ask for more!",
    "This deserves all the positive reviews it gets!",
    "High quality, reliable, and easy to use. Perfect!",
    "A high-quality product that delivers on its promises.",
    "I'm blown away by how well this works. Fantastic!",
    "Very impressed! Will definitely buy again.",
    "Great purchase. It's made my life much easier.",
    "I was hoping for something decent, but this is incredible!",
    "Trust me, you won't regret this purchase!",
    "The customer support was fantastic, and the product is excellent.",
    "Very happy with my purchase! Would recommend to anyone.",
    "It's perfect in every way! I wouldn't change a thing.",
    "I was so happy with this that I ordered another one!",
    "Amazing craftsmanship and attention to detail.",
    "It's rare to find something this good at this price.",
    "This has been a lifesaver for me. I use it every day!",
    "Couldn't have asked for a better product!",
    "I appreciate the attention to detail. It really makes a difference.",
    "You can tell this was made with care and quality in mind.",
    "Absolutely love this product! It works just as advertised.",
    "I keep recommending this to friends because it's that good.",
    "Well worth the money! Will be purchasing again.",
    "Every detail is perfect. Well done!",
    "I've never been this satisfied with a purchase before.",
    "One of my best finds this year. Highly recommend!",
    "Five stars all the way! A fantastic purchase.",
    "High quality, reliable, and easy to use. Perfect!",
    "This is easily one of the best things I own.",
    "An absolute must-have! I'm so glad I took the plunge.",
    "A must-have item in my daily routine. It's been amazing.",
    "This product has made my life so much easier. Thank you!",
    "This has been a lifesaver for me. I use it every day!",
    "I've been raving about this to my friends and family!",
    "The positive reviews were right—this is excellent!",
    "I was hoping for something decent, but this is incredible!",
    "I was hesitant, but now I can't imagine being without it.",
    "Every aspect of this product is well thought out.",
    "This is easily one of the best things I own.",
    "I was skeptical at first, but this exceeded my expectations.",
    "So worth the price! You won't be disappointed.",
    "The customer support was fantastic, and the product is excellent.",
    "So convenient and easy to use. A game-changer!",
    "Five stars all the way! A fantastic purchase.",
    "I was hoping for something decent, but this is incredible!",
    "Surprisingly good! Exceeded my expectations in every way.",
    "I'm blown away by how well this works. Fantastic!",
    "This product has become an essential part of my day.",
    "A high-quality product that delivers on its promises.",
    "The positive reviews were right—this is excellent!",
    "The reviews didn't lie—this is fantastic!",
    "Bought this as a gift, and the recipient loved it!",
    "Love the design and functionality. Such a great find!",
    "It does exactly what it says. Couldn't ask for more!",
    "A must-have item in my daily routine. It's been amazing.",
    "The customer support was fantastic, and the product is excellent.",
    "Totally satisfied! Will be buying more for my family.",
    "It's perfect in every way! I wouldn't change a thing.",
    "High quality, reliable, and easy to use. Perfect!",
    "I love products that make things simple. This is one of them.",
    "I've been raving about this to my friends and family!",
    "You can tell this was made with care and quality in mind.",
    "One of the best purchases I've ever made. Worth every penny.",
    "I've been raving about this to my friends and family!",
    "I love products that make things simple. This is one of them.",
    "I was hoping for something decent, but this is incredible!",
    "It does what it promises, and then some!",
    "One of my best finds this year. Highly recommend!",
    "I was so happy with this that I ordered another one!",
    "From packaging to performance, everything was spot on.",
    "I didn't expect it to be this good, but I was pleasantly surprised.",
    "I've tried similar products, and this one is by far the best.",
    "From the moment I received it, I knew it was a great buy.",
    "This is easily one of the best things I own.",
    "No regrets at all. In fact, I'm about to buy another one.",
    "I've tried similar products, and this one is by far the best.",
    "So convenient and easy to use. A game-changer!",
    "It does what it promises, and then some!",
    "I use this every day, and it's been a game-changer.",
    "Better than I expected! Absolutely love it.",
    "This is easily one of the best things I own.",
    "I can't stop raving about this to everyone I know.",
    "Totally worth it! I can't recommend it enough.",
    "Couldn't have asked for a better product!",
    "I love products that make things simple. This is one of them.",
    "This product has made my life so much easier. Thank you!",
    "If you're considering it, just go for it. You won't look back!",
    "An excellent buy. I would happily purchase this again.",
    "I didn't expect it to be this good, but I was pleasantly surprised.",
    "I was hesitant, but now I can't imagine being without it.",
    "The quality is top-notch. I can tell this will last a long time.",
    "I was hoping for something decent, but this is incredible!",
    "If you're on the fence, just buy it. You won't regret it.",
    "Totally satisfied! Will be buying more for my family.",
    "Every aspect of this product is well thought out.",
    "Not just good—it's amazing! So glad I got this.",
    "I've recommended this to so many people already!",
    "Absolutely love this product! It works just as advertised.",
    "Couldn't have asked for a better product!",
    "Well worth the money! Will be purchasing again.",
    "This is exactly what I was looking for. Thank you!",
    "I've recommended this to so many people already!",
    "Totally worth it! I can't recommend it enough.",
    "One of the best purchases I've ever made. Worth every penny.",
    "Not just good—it's amazing! So glad I got this.",
    "I genuinely couldn't be happier with this.",
    "Trust me, you won't regret this purchase!",
    "This has been a lifesaver for me. I use it every day!",
    "No regrets at all. In fact, I'm about to buy another one.",
    "Totally worth it! I can't recommend it enough.",
    "This is hands down the best product in its category.",
    "Love the design and functionality. Such a great find!",
    "I've never been this satisfied with a purchase before.",
    "Such a fantastic addition to my daily routine!",
    "It's rare to find something that actually works this well.",
    "After using this, I don't know how I lived without it.",
    "I love when products actually live up to the hype!",
    "I've recommended this to so many people already!",
    "From packaging to performance, everything was spot on.",
    "So worth the price! You won't be disappointed.",
    "It's rare to find something this good at this price.",
    "Incredible value for the price. Highly recommend!",
    "It does exactly what it says. Couldn't ask for more!",
    "This product proves that quality still exists!",
    "Such a fantastic addition to my daily routine!",
    "It's perfect in every way! I wouldn't change a thing.",
    "This product proves that quality still exists!",
    "I'm blown away by how well this works. Fantastic!",
    "Superb quality and fast shipping. Couldn't be happier!",
    "I keep recommending this to friends because it's that good.",
    "It's rare to find something this good at this price.",
    "A must-have item in my daily routine. It's been amazing.",
    "This is easily one of the best things I own.",
    "I appreciate the attention to detail. It really makes a difference.",
    "It does what it promises, and then some!",
    "You can tell this was made with care and quality in mind.",
    "If you're considering it, just go for it. You won't look back!",
    "This is the best thing I've purchased in a long time.",
    "An absolute must-have! I'm so glad I took the plunge.",
    "This exceeded all my expectations and more!",
    "Five stars all the way! A fantastic purchase.",
    "I was hoping for something decent, but this is incredible!",
    "From the moment I received it, I knew it was a great buy.",
    "I was so happy with this that I ordered another one!",
    "The customer support was fantastic, and the product is excellent.",
    "This is the best thing I've purchased in a long time.",
    "Every aspect of this product is well thought out.",
    "If you're considering it, just go for it. You won't look back!",
    "I love products that make things simple. This is one of them.",
    "Totally satisfied! Will be buying more for my family.",
    "Great purchase. It's made my life much easier.",
    "This product is a gem! I wish I had bought it sooner.",
    "I didn't expect it to be this good, but I was pleasantly surprised.",
    "Perfect in every way. I will be purchasing again.",
    "I didn't expect it to be this good, but I was pleasantly surprised.",
    "A must-have item in my daily routine. It's been amazing.",
    "A must-have for anyone who values reliability.",
    "One of the best purchases I've ever made. Worth every penny.",
    "The quality is top-notch. I can tell this will last a long time.",
    "From packaging to performance, everything was spot on.",
    "Perfect in every way. I will be purchasing again.",
    "Totally worth it! I can't recommend it enough.",
    "You can tell this was made with care and quality in mind.",
    "I've recommended this to so many people already!",
    "Love the design and functionality. Such a great find!",
    "After using this, I don't know how I lived without it.",
    "I didn't expect it to be this good, but I was pleasantly surprised.",
    "So simple yet so effective. Love it!",
    "I keep recommending this to friends because it's that good.",
    "Trust me, you won't regret this purchase!",
    "Fantastic quality. Would give it 10 stars if I could!",
    "An absolute must-have! I'm so glad I took the plunge.",
    "I'm blown away by how well this works. Fantastic!",
    "My expectations were high, and this still managed to exceed them.",
    "High quality, reliable, and easy to use. Perfect!",
    "Totally worth it! I can't recommend it enough.",
    "I can't stop raving about this to everyone I know.",
    "Totally worth it! I can't recommend it enough.",
    "High quality, reliable, and easy to use. Perfect!",
    "Absolutely love this product! It works just as advertised.",
    "I appreciate the attention to detail. It really makes a difference.",
    "Amazing craftsmanship and attention to detail.",
    "It's perfect in every way! I wouldn't change a thing.",
    "A must-have item in my daily routine. It's been amazing.",
    "My expectations were high, and this still managed to exceed them.",
    "This product has made my life so much easier. Thank you!",
    "This is easily one of the best things I own.",
    "Trust me, you won't regret this purchase!",
    "Such a fantastic addition to my daily routine!",
    "Very happy with my purchase! Would recommend to anyone.",
    "From the moment I received it, I knew it was a great buy.",
    "It's rare to find something this good at this price.",
    "Very impressed! Will definitely buy again.",
    "I appreciate the attention to detail. It really makes a difference.",
    "A high-quality product that delivers on its promises.",
    "This deserves all the positive reviews it gets!",
    "Every detail is perfect. Well done!",
    "Perfect in every way. I will be purchasing again.",
    "A must-have item in my daily routine. It's been amazing.",
    "Great purchase. It's made my life much easier.",
    "An absolute must-have! I'm so glad I took the plunge.",
    "From the moment I received it, I knew it was a great buy.",
    "I genuinely couldn't be happier with this.",
    "This product proves that quality still exists!",
    "I can't stop raving about this to everyone I know.",
    "This exceeded all my expectations and more!",
    "This product is a gem! I wish I had bought it sooner.",
    "I was hoping for something decent, but this is incredible!",
    "The positive reviews were right—this is excellent!",
    "I'd buy this again in a heartbeat!",
    "The customer support was fantastic, and the product is excellent.",
    "A must-have for anyone who values reliability.",
    "No regrets at all. In fact, I'm about to buy another one.",
    "Very impressed! Will definitely buy again.",
    "Great purchase. It's made my life much easier.",
    "I was hesitant, but now I can't imagine being without it.",
    "A must-have item in my daily routine. It's been amazing.",
    "So simple yet so effective. Love it!",
    "It's perfect in every way! I wouldn't change a thing.",
    "Love the design and functionality. Such a great find!",
    "I love when products actually live up to the hype!",
    "Very happy with my purchase! Would recommend to anyone.",
    "Well worth the money! Will be purchasing again.",
    "I love when products actually live up to the hype!",
    "Trust me, you won't regret this purchase!",
    "I keep recommending this to friends because it's that good.",
    "This deserves all the positive reviews it gets!",
    "Totally satisfied! Will be buying more for my family.",
    "This has been a lifesaver for me. I use it every day!",
    "A must-have for anyone who values reliability.",
    "I've tried similar products, and this one is by far the best.",
    "I was hesitant, but now I can't imagine being without it.",
    "It's rare to find something this good at this price.",
    "Amazing craftsmanship and attention to detail.",
    "A high-quality product that delivers on its promises.",
    "I was skeptical at first, but this exceeded my expectations.",
    "Very impressed! Will definitely buy again.",
    "From packaging to performance, everything was spot on.",
    "The positive reviews were right—this is excellent!",
    "This is easily one of the best things I own.",
    "One of my best finds this year. Highly recommend!",
    "I've tried similar products, and this one is by far the best.",
    "Such a fantastic addition to my daily routine!",
    "The quality is top-notch. I can tell this will last a long time.",
    "An excellent buy. I would happily purchase this again.",
    "I'd buy this again in a heartbeat!",
    "This product has earned a permanent place in my home.",
    "This product has become an essential part of my day.",
    "If you're on the fence, just buy it. You won't regret it.",
    "It's perfect in every way! I wouldn't change a thing.",
    "Amazing craftsmanship and attention to detail.",
    "It does what it promises, and then some!",
    "I love when products actually live up to the hype!",
    "Trust me, you won't regret this purchase!",
    "I use this every day, and it's been a game-changer.",
    "This is easily one of the best things I own.",
    "Better than I expected! Absolutely love it.",
    "I use this every day, and it's been a game-changer.",
    "The positive reviews were right—this is excellent!",
    "Totally satisfied! Will be buying more for my family.",
    "I keep recommending this to friends because it's that good.",
    "One of the best purchases I've ever made. Worth every penny.",
    "Every aspect of this product is well thought out.",
    "I keep recommending this to friends because it's that good.",
    "This product has become an essential part of my day.",
    "Superb quality and fast shipping. Couldn't be happier!",
    "It does what it promises, and then some!",
    "I use this every day, and it's been a game-changer.",
    "Better than I expected! Absolutely love it.",
    "If you're on the fence, just buy it. You won't regret it.",
    "Very impressed! Will definitely buy again.",
    "Bought this as a gift, and the recipient loved it!",
    "This product has made my life so much easier. Thank you!",
    "Five stars all the way! A fantastic purchase.",
    "Every aspect of this product is well thought out.",
    "I love products that make things simple. This is one of them.",
    "It does what it promises, and then some!",
    "One of my best finds this year. Highly recommend!",
    "Superb quality and fast shipping. Couldn't be happier!",
    "High quality, reliable, and easy to use. Perfect!",
    "Quality is unmatched. I highly recommend this product.",
    "I never write reviews, but this product deserves one.",
    "The customer support was fantastic, and the product is excellent.",
    "I've never been this satisfied with a purchase before.",
    "An excellent buy. I would happily purchase this again.",
    "I've been raving about this to my friends and family!",
    "Totally worth it! I can't recommend it enough.",
    "This is exactly what I was looking for. Thank you!",
    "The reviews didn't lie—this is fantastic!",
    "Surprisingly good! Exceeded my expectations in every way.",
    "I keep recommending this to friends because it's that good.",
    "Well worth the money! Will be purchasing again.",
    "Incredible value for the price. Highly recommend!",
    "No regrets at all. In fact, I'm about to buy another one.",
    "It's perfect in every way! I wouldn't change a thing.",
    "I've never been this satisfied with a purchase before.",
    "Five stars all the way! A fantastic purchase.",
    "One of the best investments I've made in a while.",
    "I'd buy this again in a heartbeat!",
    "A must-have item in my daily routine. It's been amazing.",
    "Totally worth it! I can't recommend it enough.",
    "I've tried similar products, and this one is by far the best.",
    "This is easily one of the best things I own.",
    "This product has become an essential part of my day.",
    "Not just good—it's amazing! So glad I got this.",
    "I was skeptical at first, but this exceeded my expectations.",
    "This is hands down the best product in its category.",
    "Fantastic quality. Would give it 10 stars if I could!",
    "Very impressed! Will definitely buy again.",
    "I was hesitant, but now I can't imagine being without it.",
    "An excellent buy. I would happily purchase this again.",
    "This product is a gem! I wish I had bought it sooner.",
    "A must-have for anyone who values reliability.",
    "Superb in every way. I'm genuinely impressed!",
    "A must-have for anyone who values reliability.",
    "This has been a lifesaver for me. I use it every day!",
    "So simple yet so effective. Love it!",
    "My expectations were high, and this still managed to exceed them.",
    "This is easily one of the best things I own.",
    "Every aspect of this product is well thought out.",
    "Superb in every way. I'm genuinely impressed!",
    "I'm blown away by how well this works. Fantastic!",
    "You can tell this was made with care and quality in mind.",
    "The quality is top-notch. I can tell this will last a long time.",
    "This is easily one of the best things I own.",
    "Well worth the money! Will be purchasing again.",
    "If you're on the fence, just buy it. You won't regret it.",
    "I'd buy this again in a heartbeat!",
    "High quality, reliable, and easy to use. Perfect!",
    "So worth the price! You won't be disappointed.",
    "After using this, I don't know how I lived without it.",
    "So simple yet so effective. Love it!",
    "I didn't expect it to be this good, but I was pleasantly surprised.",
    "One of my best finds this year. Highly recommend!",
    "Great purchase. It's made my life much easier.",
    "Every detail is perfect. Well done!",
    "A friend recommended this, and now I see why!",
    "I didn't expect it to be this good, but I was pleasantly surprised.",
    "From the moment I received it, I knew it was a great buy.",
    "Totally satisfied! Will be buying more for my family.",
    "I was skeptical at first, but this exceeded my expectations.",
    "Every aspect of this product is well thought out.",
    "The quality is top-notch. I can tell this will last a long time.",
    "Absolutely love this product! It works just as advertised.",
    "Superb in every way. I'm genuinely impressed!",
    "Quality is unmatched. I highly recommend this product.",
    "This product proves that quality still exists!",
    "This product has become an essential part of my day.",
    "Very impressed! Will definitely buy again.",
    "Superb in every way. I'm genuinely impressed!",
    "This product has become an essential part of my day.",
    "This is hands down the best product in its category.",
    "Very impressed! Will definitely buy again.",
    "This deserves all the positive reviews it gets!",
    "I love when products actually live up to the hype!",
    "I keep recommending this to friends because it's that good.",
    "Superb in every way. I'm genuinely impressed!",
    "An absolute must-have! I'm so glad I took the plunge.",
    "It does exactly what it says. Couldn't ask for more!",
    "High quality, reliable, and easy to use. Perfect!",
    "This is easily one of the best things I own.",
    "Trust me, you won't regret this purchase!",
    "I genuinely couldn't be happier with this.",
    "I use this every day, and it's been a game-changer.",
    "If you're on the fence, just buy it. You won't regret it.",
    "This product has made my life so much easier. Thank you!",
    "You can tell this was made with care and quality in mind.",
    "I appreciate the attention to detail. It really makes a difference.",
    "Not just good—it's amazing! So glad I got this.",
    "Trust me, you won't regret this purchase!",
    "This is hands down the best product in its category.",
    "I'd buy this again in a heartbeat!",
    "This has been a lifesaver for me. I use it every day!",
    "You can tell this was made with quality in mind."
      "Absolutely fantastic product!",
            "Exceeded all my expectations!",
            "Best purchase I've made this year!",
            "Highly recommend this to everyone!",
            "I'm in love with this product!",
            "Super easy to use and works like a charm!",
            "This is a must-have!",
            "Incredible quality for the price!",
            "Such a great value, I would buy it again!",
            "Amazing craftsmanship and attention to detail!",
            "This product is life-changing!",
            "I'm blown away by the performance!",
            "The best solution for my needs!",
            "Perfect in every way!",
            "I can't stop recommending this to my friends!",
            "This product deserves more than 5 stars!",
            "So simple yet so effective!",
            "It made my life so much easier!",
            "Premium quality at an affordable price!",
            "I'm extremely satisfied with my purchase!",
            "Better than I ever imagined!",
            "This is exactly what I needed!",
            "Couldn't have asked for a better product!",
            "I would buy this again in a heartbeat!",
            "The quality is simply outstanding!",
            "I'm so glad I gave this a try!",
            "Perfect for daily use!",
            "It's been a game-changer for me!",
            "I can't believe I didn't buy this sooner!",
            "The best investment I've made in a while!",
            "Fantastic product with top-notch service!",
            "The packaging was perfect and secure!",
            "I love everything about this!",
            "A product that truly delivers on its promise!",
            "I was skeptical at first, but it's amazing!",
            "I will definitely be buying more!",
            "So glad I found this!",
            "This has become an essential part of my routine!",
            "It works even better than I expected!",
            "The design is both stylish and functional!",
            "Every detail is carefully crafted!",
            "A perfect gift for anyone!",
            "I can't stop using it!",
            "A must-have in every household!",
            "This has exceeded my wildest expectations!",
            "The performance is top-notch!",
            "This product is truly innovative!",
            "The comfort level is unreal!",
            "I received so many compliments on this!",
            "It feels like a luxury product!",
            "Even better than the premium brands!",
            "I can't imagine my life without it now!",
            "One of the smartest purchases I've made!",
            "The perfect combination of beauty and functionality!",
            "I love how convenient this is!",
            "This made my tasks so much easier!",
            "I can tell a lot of thought went into this product!",
            "Incredible innovation at a great price!",
            "I genuinely love using this every day!",
            "This is the gold standard of its kind!",
            "An absolute joy to use!",
            "I look forward to using it every day!",
            "This product is a lifesaver!",
            "So lightweight and easy to carry around!",
            "Perfect for my needs and works like a dream!",
            "I love the versatility of this!",
            "This exceeded my high expectations!",
            "It makes everything so much easier!",
            "I will be purchasing more for my family!",
            "You won't regret buying this!",
            "Hands down the best on the market!",
            "This makes me feel like a professional!",
            "I wish I had known about this sooner!",
            "This is my go-to product from now on!",
            "It looks and feels premium!",
            "This is one of the best things I've ever purchased!",
            "Great customer service and a fantastic product!",
            "I can't stop raving about this!",
            "The build quality is exceptional!",
            "I love how effortless this is to use!",
            "This makes my daily tasks so much more enjoyable!",
            "This is exactly what I was looking for!",
            "I am beyond thrilled with my purchase!",
            "Amazing product and quick shipping!",
            "It's even better than advertised!",
            "Such a well-thought-out product!",
            "This has completely changed my workflow!",
            "I wouldn't trade this for anything!",
            "I never leave home without it!",
            "This is my new favorite item!",
            "I am so happy with this product!",
            "This is the definition of excellence!",
            "Unmatched quality and performance!",
            "I feel like I got more than my money's worth!",
            "I can't stop smiling every time I use it!",
            "A fantastic addition to my daily routine!",
            "I love how durable this is!",
            "You can tell this is made to last!",
            "I've never been more satisfied with a purchase!",
            "So glad I made the decision to buy this!",
            "It's like it was made just for me!",
            "I'm never going back to my old product!",
            "This is an absolute must-buy!",
            "It arrived in perfect condition!",
            "This gives me so much confidence!",
            "I love how well it fits my needs!",
            "This exceeded every expectation I had!",
            "I've already recommended it to my entire family!",
            "Simply put: it's amazing!",
            "Everything about this is just right!",
            "It looks as good as it works!",
            "This has made a huge difference in my daily life!",
            "So elegant and effective at the same time!",
            "This is hands down my favorite purchase this year!",
            "I'm absolutely thrilled with this product!",
            "I wouldn't change a single thing about it!",
            "I wish I could give it more than five stars!",
            "An absolute masterpiece!",
            "I'm so impressed with how well it performs!",
            "I feel like I hit the jackpot with this one!",
            "Flawless design and execution!",
            "This product brings me so much joy!",
    
            None  # Some reviews will have no comments
        ])
    }

# Generate review data
reviews = [generate_review(user_id=i, product_id=random.randint(1, 300), branch_id=random.randint(1, 260)) for i in range(1, NUM_REVIEWS + 1)]

# Save to JSON file
with open("reviews.json", "w") as json_file:
    json.dump(reviews, json_file, indent=4)

print(f"✅ Successfully saved {NUM_REVIEWS} reviews to reviews.json")
