import json
import random

# Define the number of reviews to generate
NUM_REVIEWS = 500

COMMENTS = [
    "Perfectly seasoned and full of flavor,",
"Deliciously fresh ingredients in every bite,",
"Mouthwatering aroma filled the room immediately,",
"Exceptional balance of sweet and savory notes,",
"Texture was spot-on for this dish,",
"Generous portions that satisfied completely,",
"Beautifully presented on the plate,",
"Flavors melded together wonderfully,",
"Cooked to absolute perfection,",
"Ingredients tasted remarkably fresh,",
"Pleasantly surprised by the unique flavor combination,",
"Authentic taste that transported me instantly,",
"Exceptional quality for the price point,",
"Perfectly cooked with just the right tenderness,",
"Spice level was exactly as requested,",
"Rich, complex flavors in every bite,",
"Artfully plated with careful attention to detail,",
"Wonderful depth of flavor throughout,",
"Temperature was ideal when served,",
"Consistency was exactly what I hoped for,",
"Delicate balance of herbs and spices,",
"Absolutely worth ordering again,",
"Impressive attention to flavor composition,",
"Satisfying meal from start to finish,",
"Quality ingredients that truly stand out,",
"Perfect portion size for one sitting,",
"Subtle nuances of flavor came through beautifully,",
"Every ingredient complemented the others perfectly,",
"Delightful contrast of textures throughout,",
"Refreshingly light yet completely satisfying,",
"Comforting food that exceeded expectations,",
"Expertly prepared with obvious care,",
"Distinctive flavor profile unlike anything else,",
"Harmonious blend of traditional elements,",
"Remarkably fresh and vibrant taste,",
"Savory goodness in every spoonful,",
"Impressive quality of ingredients throughout,",
"Perfectly balanced sauce that enhanced everything,",
"Crave-worthy dish I'll definitely order again,",
"Hearty satisfaction in every portion,",
"Thoughtfully composed plate of food,",
"Textures worked together beautifully,",
"Incredible depth of flavor for such a simple dish,",
"Perfectly executed classic recipe,",
"Rich taste without being overwhelming,",
"Remarkably authentic regional flavors,",
"Fresh ingredients that clearly made a difference,",
"Wonderful interplay of sweet and spicy notes,",
"Satisfying crunch in every bite,",
"Every component cooked to perfection,",
"Melt-in-your-mouth tenderness throughout,",
"Delightfully aromatic presentation,",
"Savory umami flavor that lingered pleasantly,",
"Exactly the comfort food I was craving,",
"Stunning presentation that matched the taste,",
"Layers of flavor unfolded with each bite,",
"Perfect temperature when it arrived,",
"Distinctively fresh taste in every ingredient,",
"Satisfying texture from first bite to last,",
"Masterfully balanced spice profile,",
"Robust flavors that complemented each other,",
"Excellent quality ingredients throughout,",
"Perfectly seasoned without being salty,",
"Memorable meal worth recommending,",
"Delicate flavors that really impressed,",
"Expertly crafted culinary delight,",
"Satisfying portion that left me content,",
"Wonderful marriage of flavors and textures,",
"Impeccably fresh seafood that tasted amazing,",
"Harmonious blend of traditional spices,",
"Beautifully cooked to the perfect doneness,",
"Rich sauce that complemented perfectly,",
"Surprisingly complex flavor profile,",
"Delightfully crisp exterior with tender inside,",
"Perfect level of moisture throughout,",
"Impressive consistency between visits,",
"Remarkably authentic ethnic flavors,",
"Clearly made with high-quality ingredients,",
"Bold flavors that weren't overwhelming,",
"Satisfying combination of fresh elements,",
"Perfect balance of acidity and richness,",
"Beautifully layered flavor experience,",
"Expertly prepared traditional recipe,",
"Exceptional freshness evident in every bite,",
"Melt-in-your-mouth texture that impressed,",
"Perfectly executed fusion of cuisines,",
"Rich depth that showed culinary expertise,",
"Delicately spiced to highlight natural flavors,",
"Remarkably well-balanced dish overall,",
"Fresh herbs added the perfect touch,",
"Consistently excellent quality every visit,",
"Wonderful aroma that enhanced the experience,",
"Perfectly portioned for complete satisfaction,",
"Impressive attention to cooking technique,",
"Distinctively homemade taste and quality,",
"Incredibly fresh ingredients throughout,",
"Perfect harmony of contrasting flavors,",
"Expertly seared to lock in flavor,",
"Satisfying meal that left a great impression,",
"Wonderful complexity without being complicated,",
"Beautifully balanced sweet and savory elements,",
"Perfect temperature retention throughout the meal,",
"Remarkably flavorful for such a simple preparation,",
"Exceptional quality that justified the price,",
"Delightful contrast between soft and crunchy textures,",
"Masterfully seasoned throughout each layer,",
"Perfect level of heat that built pleasantly,",
"Brilliantly executed signature dish,",
"Noticeably superior ingredient quality,",
"Satisfying richness without being heavy,",
"Perfect doneness that showed skill,",
"Bright, fresh flavors that impressed immediately,",
"Exceptionally tender throughout the entire cut,",
"Remarkable depth for such a straightforward dish,",
"Carefully balanced sweetness that wasn't overpowering,",
"Perfect crisp exterior with ideal interior,",
"Generous portion of the highest quality,",
"Expertly prepared with obvious attention to detail,",
"Wonderful smoky notes that added complexity,",
"Perfectly cooked to my exact preference,",
"Consistently excellent with each visit,",
"Remarkable freshness that made all the difference,",
"Beautifully composed plate with attention to color,",
"Perfect balance of richness and acidity,",
"Delightfully unexpected flavor combinations,",
"Exceptional technique evident in every bite,",
"Satisfying texture that kept me engaged,",
"Wonderfully fragrant dish from first approach,",
"Perfectly sauced without drowning the ingredients,",
"Bright flavor profile that stood out,",
"Remarkably well-executed classic preparation,",
"Distinctively homemade taste that impressed,",
"Excellent mixture of textures throughout,",
"Perfectly balanced flavor composition,",
"Subtle complexity that developed with each bite,",
"Impressive attention to regional authenticity,",
"Delightfully light yet satisfying experience,",
"Wonderful interplay between all components,",
"Exceptionally fresh produce that stood out,",
"Perfect execution of a difficult technique,",
"Remarkably well-balanced spice blend,",
"Beautifully seared exterior with perfect interior,",
"Memorable flavor combination I'll crave again,",
"Delicate seasoning that enhanced natural flavors,",
"Impeccably cooked protein at perfect temperature,",
"Wonderful harmonic blend of ingredients,",
"Perfectly structured dish with thoughtful assembly,",
"Rich without being overly heavy,",
"Exceptional contrast between elements,",
"Pleasantly surprising complexity of flavor,",
"Perfect ratio of components in each bite,",
"Brilliantly conceptualized flavor pairing,",
"Remarkable tenderness achieved throughout,",
"Delightfully aromatic from the moment it arrived,",
"Expertly judged cooking time evident in texture,",
"Wonderful depth from slow cooking process,",
"Perfectly crisp where it should be,",
"Impressive consistency in quality,",
"Remarkably intense flavor in such a light dish,",
"Satisfying meal that hit all the right notes,",
"Excellent attention to temperature contrast,",
"Perfectly balanced dish in every aspect,",
"Brilliantly executed culinary technique,",
"Notable freshness in every component,",
"Delightfully nuanced flavor profile,",
"Expertly charred exterior with juicy interior,",
"Amazing textural contrast throughout,",
"Perfectly reduced sauce with ideal consistency,",
"Exceptional quality ingredients clearly used,",
"Wonderful combination of familiar flavors,",
"Perfectly cooked to retain natural moisture,",
"Impressive execution of traditional recipe,",
"Remarkably well-developed flavor depth,",
"Beautifully caramelized exterior notes,",
"Distinctive house-made quality evident,",
"Perfectly portioned elements in each bite,",
"Delightfully harmonious ingredient combination,",
"Exceptional attention to textural contrast,",
"Wonderful seasoning that built with each taste,",
"Perfectly tender results that impressed,",
"Impressive richness without heaviness,",
"Remarkably clean flavors throughout,",
"Masterfully balanced sweet and salty notes,",
"Delightful freshness in every component,",
"Expertly composed plate with beautiful height,",
"Wonderfully aromatic herbs used perfectly,",
"Perfect sear that enhanced flavor dramatically,",
"Reliable excellence with each order,",
"Remarkable depth from proper reduction,",
"Satisfying umami presence throughout,",
"Excellent temperature when served,",
"Perfectly executed cooking technique,",
"Distinguished by exceptional freshness,",
"Skillfully prepared with obvious expertise,",
"Wonderful balance of bold elements,",
"Perfectly moisture-controlled throughout,",
"Impressively authentic ethnic flavors,",
"Notable quality ingredients throughout,",
"Delicately seasoned to perfection,",
"Expert preparation evident in every bite,",
"Wonderful caramelization that added complexity,",
"Perfect texture achieved in every element,",
"Remarkable flavor development apparent,",
"Beautifully rustic yet refined presentation,",
"Distinctive taste that sets it apart,",
"Perfectly balanced acidity in the sauce,",
"Delightfully unexpected taste combination,",
"Exceptional consistency between visits,",
"Wonderful mouthfeel from first bite to last,",
"Perfectly judged cooking time for each component,",
"Impressively layered flavor construction,",
"Remarkably light yet deeply satisfying,",
"Skillfully handled delicate ingredients,",
"Wonderful textural journey throughout,",
"Perfect level of charring for flavor,",
"Expertly seasoned at every level,",
"Satisfying density with perfect chew,",
"Excellent flavor clarity in every component,",
"Perfect fusion of cultural influences,",
"Delightfully aromatic herbs used generously,",
"Impressively consistent quality every time,",
"Remarkable respect for the main ingredient,",
"Skillfully balanced richness and brightness,",
"Wonderfully authentic traditional preparation,",
"Perfect temperature gradient throughout,",
"Expertly composed flavor architecture,",
"Satisfyingly harmonious combination throughout,",
"Excellent contrast between components,",
"Perfectly rendered fat adding rich flavor,",
"Impressively prepared complex dish,",
"Remarkable flavor intensity without heaviness,",
"Beautifully developed sauce reduction,",
"Distinctive house specialty worth returning for,",
"Perfectly balanced sweetness throughout,",
"Expertly achieved textural contrast,",
"Wonderful depth from proper searing,",
"Perfect ratio of sauce to main component,",
"Remarkably well-executed technical challenge,",
"Delightfully subtle flavor nuances,",
"Expertly crafted traditional preparation,",
"Wonderful flavor progression with each bite,",
"Perfect crispness without dryness,",
"Impressively authentic regional specialty,",
"Remarkably fresh ingredients clearly used,",
"Skillfully prepared delicate components,",
"Wonderful integration of seasonal elements,",
"Perfect doneness showing chef's expertise,",
"Exceptionally well-balanced flavor profile,",
"Delightfully unexpected textural surprise,",
"Expertly rendered crispy exterior,",
"Wonderful depth from careful preparation,",
"Perfect execution of difficult technique,",
"Remarkably consistent quality maintained,",
"Satisfyingly complex yet harmonious,",
"Excellent brightness that cut through richness,",
"Perfect marriage of contrasting elements,",
"Delightfully aromatic presentation,",
"Impressive showcase of ingredient quality,",
"Remarkably well-developed flavor base,",
"Beautifully presented with careful garnishing,",
"Distinctive house interpretation of a classic,",
"Perfectly judged seasoning throughout,",
"Expertly balanced sweet and sour notes,",
"Wonderful richness without overwhelming,",
"Perfect consistency throughout the dish,",
"Impressively executed technical preparation,",
"Remarkable depth for such simple ingredients,",
"Skillfully balanced spices and herbs,",
"Wonderful textural interplay between elements,",
"Perfect temperature contrast within dish,",
"Exceptionally tender result achieved,",
"Delightfully nuanced flavor development,",
"Expertly integrated international influences,",
"Wonderful harmony of complex components,",
"Perfect execution of a signature item,",
"Remarkably authentic traditional flavors,",
"Masterfully balanced sauce accompaniment,",
"Excellent layering of complementary flavors,",
"Perfect cooking time evident in texture,",
"Delightfully surprising flavor combination,",
"Impressively consistent quality standard,",
"Remarkable freshness that stood out immediately,",
"Beautifully achieved caramelization,",
"Distinctive chef's interpretation impressed,",
"Perfectly judged acidity balance,",
"Expertly handled delicate cooking process,",
"Wonderful complexity that developed gradually,",
"Perfect texture contrast throughout,",
"Remarkably well-structured flavor profile,",
"Delicate ingredients treated with respect,",
"Expertly layered complementary elements,",
"Wonderful herbal notes that enhanced everything,",
"Perfect balance of richness and lightness,",
"Impressively executed culinary technique,",
"Remarkably clean yet complex flavor,",
"Skillfully achieved depth in a simple dish,",
"Wonderful synthesis of diverse elements,",
"Perfect tenderness throughout the protein,",
"Exceptionally fresh seasonal ingredients,",
"Delightfully balanced sweet and spicy notes,",
"Expertly crafted house specialty,",
"Wonderful counterpoint of textures,",
"Perfect execution of traditional method,",
"Remarkably refined rustic preparation,",
"Beautifully presented home-style cooking,",
"Distinctive flavor signature recognizable immediately,",
"Perfectly rendered crisp exterior layer,",
"Expertly balanced accompanying sauce,",
"Wonderful integration of acidic elements,",
"Perfect portion of each component,",
"Impressively maintained moisture throughout,",
"Remarkable concentration of natural flavors,",
"Skillfully constructed flavor composition,",
"Wonderful aroma that enhanced anticipation,",
"Perfect cooking technique clearly demonstrated,",
"Exceptionally well-realized concept dish,",
"Delightfully unexpected flavor twist,",
"Expertly achieved texture throughout,",
"Wonderful harmony of complex notes,",
"Perfect seasoning from first to last bite,",
"Remarkably well-executed fusion concept,",
"Masterfully controlled cooking temperature,",
"Excellent quality control evident throughout,",
"Perfect balance of bold flavors,",
"Delightfully aromatic spice blend,",
"Impressively authentic cultural preparation,",
"Remarkable umami depth achieved,",
"Beautiful knife work evident in presentation,",
"Distinctive house preparation worth trying,",
"Perfectly consistent texture throughout,",
"Expertly balanced richness and acidity,",
"Wonderful complexity from skillful technique,",
"Perfect execution of timing-sensitive dish,",
"Remarkably nuanced flavor development,",
"Carefully prepared traditional recipe,",
"Excellently judged cooking duration,",
"Wonderful seasonal ingredients showcased well,",
"Perfect moisture retention throughout,",
"Impressively harmonious combination of elements,",
"Remarkably delicate flavor balance,",
"Skillfully achieved textural contrast,",
"Wonderful depth from proper reduction,",
"Perfect temperature upon serving,",
"Exceptionally well-balanced overall composition,",
"Delightfully surprising palate journey,",
"Expertly crafted sauce accompaniment,",
"Wonderful interplay between components,",
"Perfect doneness showing technical skill,",
"Remarkably clean flavor definition,",
"Beautiful presentation without being pretentious,",
"Distinctive house specialty worth ordering,",
"Perfectly seasoned throughout each layer,",
"Expertly balanced portion composition,",
"Wonderful marriage of tradition and innovation,",
"Perfect texture gradient achieved,",
"Impressively authentic regional preparation,",
"Remarkable flavor concentration evident,",
"Skillfully executed technical challenge,",
"Wonderful contrast between elements,",
"Perfect harmony of sweet and bitter notes,",
"Exceptionally well-developed flavor base,",
"Delightfully crisp where intended,",
"Expertly timed cooking process evident,",
"Wonderful depth from proper technique,",
"Perfect tenderness achieved throughout,",
"Remarkably balanced eating experience,",
"Masterfully handled delicate ingredients,",
"Excellent textural variation throughout,",
"Perfect spice level for the dish,",
"Delightfully fragrant from first approach,",
"Impressively consistent preparation standard,",
"Remarkable freshness in seasonal elements,",
"Beautifully achieved sear on the protein,",
"Distinctive flavor profile that impressed,",
"Perfectly judged salt level throughout,",
"Expertly crafted sauce consistency,",
"Wonderful balance of contrasting flavors,",
"Perfect execution of difficult technique,",
"Remarkably well-integrated flavor components,",
"Delicate elements treated with expertise,",
"Expertly layered complementary flavors,",
"Wonderful amalgamation of diverse ingredients,",
"Perfect moisture control throughout cooking,",
"Impressively executed classic preparation,",
"Remarkably clean yet complex profile,",
"Skillfully achieved depth and dimension,",
"Wonderful textural journey in each bite,",
"Perfect temperature consistency throughout,",
"Exceptionally fresh ingredients evident,",
"Delightfully balanced flavor composition,",
"Expertly constructed traditional dish,",
"Wonderful contrast in complementary elements,",
"Perfect execution of heritage recipe,",
"Remarkably refined home-style cooking,",
"Beautifully presented rustic preparation,",
"Distinctive chef's interpretation evident,",
"Perfectly balanced acidity throughout,",
"Expertly judged cooking temperature,",
"Wonderful richness without heaviness,",
"Perfect seasoning showcasing natural flavors,",
"Impressively maintained quality consistency,",
"Remarkable depth from slow preparation,",
"Skillfully balanced multiple flavor notes,",
"Wonderful interplay of temperatures,",
"Perfect cooking technique demonstrated,",
"Exceptionally well-conceived dish execution,",
"Delightfully unexpected flavor pairing,",
"Expertly achieved textural composition,",
"Wonderful complexity built methodically,",
"Perfect balance throughout the experience,",
"Remarkably well-executed technical preparation,",
"Masterfully controlled cooking process,",
"Excellent ingredients clearly sourced carefully,",
"Perfect ratio of complementary components,",
"Delightfully aromatic herb usage,",
"Impressively authentic traditional preparation,",
"Remarkable umami richness developed,",
"Beautiful presentation enhancing appetite,",
"Distinctive house recipe worth returning for,",
"Perfectly consistent quality throughout,",
"Expertly balanced sweetness in the dish,",
"Wonderful depth from proper preparation,",
"Perfect texture achieved in protein,",
"Remarkably nuanced spice application,",
"Carefully constructed flavor architecture,",
"Excellently judged cooking duration,",
"Wonderful seasonal influence evident,",
"Perfect moisture balance throughout,",
"Impressively harmonious flavor combination,",
"Remarkably delicate touch evident,",
"Skillfully achieved contrast in textures,",
"Wonderful depth from careful technique,",
"Perfect temperature maintenance throughout,",
"Exceptionally well-balanced overall composition,",
"Delightfully surprising flavor development,",
"Expertly crafted accompanying elements,",
"Wonderful integration of components,",
"Perfect doneness showcasing expertise,",
"Remarkably clean flavor separation,",
"Beautiful plating enhancing experience,",
"Distinctive interpretation of traditional dish,",
"Perfectly judged seasoning balance,",
"Expertly controlled heat application,",
"Wonderful marriage of familiar elements,",
"Perfect textural composition achieved,",
"Impressively authentic ethnic preparation,",
"Remarkable flavor progression evident,",
"Skillfully executed specialty technique,",
"Wonderful balance throughout each bite,",
"Perfect harmony between contrasting notes,",
"Exceptionally well-developed base flavors,",
"Delightfully crisp exterior achieved,",
"Expertly timed cooking evident in result,",
"Wonderful depth from skilled preparation,",
"Perfect tenderness consistently throughout,",
"Remarkably balanced eating experience,",
"Masterfully handled temperature control,",
"Excellent textural consideration throughout,",
"Perfect spice blend for this dish,",
"Delightfully aromatic presentation,",
"Impressively consistent between visits,",
"Remarkable freshness in every component,",
"Beautifully executed searing technique,",
"Distinctive flavor profile immediately evident,",
"Perfectly judged salt balance throughout,",
"Expertly prepared sauce consistency,",
"Wonderful contrast between elements,",
"Perfect execution of challenging preparation,",
"Remarkably well-integrated ingredients,",
"Delicate flavors preserved skillfully,",
"Expertly combined complementary tastes,",
"Wonderful harmony throughout the dish,",
"Perfect moisture retention in cooking,",
"Impressively executed signature dish,",
"Remarkably clean flavor definition,",
"Skillfully achieved texture variation,",
"Wonderful sensory experience overall,",
"Perfect temperature gradient maintained,",
"Exceptionally fresh seasonal elements,",
"Delightfully balanced overall experience,",
"Expertly refined traditional approach,",
"Wonderful contrast in complementary components,",
"Perfect execution of classic preparation,",
"Remarkably accurate flavor reproduction,",
"Beautifully presented with careful attention,",
"Distinctive chef's creativity evident,",
"Perfectly balanced acidity and sweetness,",
"Expertly judged cooking precision,",
"Wonderful richness appropriately controlled,",
"Perfect seasoning enhancing natural flavors,",
"Impressively consistent quality standard,",
"Remarkable depth from proper technique,",
"Skillfully balanced multiple elements,",
"Wonderful play of temperatures throughout,",
"Perfect cooking technique demonstrated,",
"Exceptionally well-conceived overall dish,",
"Delightfully surprising taste combination,",
"Expertly achieved textural interplay,",
"Wonderful complex flavor architecture,",
"Perfect harmony throughout the experience,"
]


# Shuffle the comments to ensure randomness
random.shuffle(COMMENTS)

# Generate review data
reviews = [{"comments": comment} for comment in COMMENTS[:NUM_REVIEWS]]

# Save to JSON file
with open("food.json", "w") as json_file:
    json.dump(reviews, json_file, indent=4)

print(f"✅ Successfully saved {len(reviews)} unique reviews to shop_online.json")
